name: Delete old workflow runs
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_call:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
