name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup C Compiler
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gcc-7-multilib
    - name: Setup Build Directories
      run: |
        ./build_helper/github/setup.sh ${{ github.event.inputs.version }}
    - name: Compile
      run: |
        ./build_helper/github/compile.sh ${{ github.event.inputs.version }}
    - name: Compress
      run: |
        ./build_helper/github/compress.sh ${{ github.event.inputs.version }}
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        name: ehdd-v${{ github.event.inputs.version }}
        tag_name: v${{ github.event.inputs.version }}
        fail_on_unmatched_files: true
        files: |
          *.tar.gz
        draft: true
        prerelease: false
    - name: Build Info
      run: |
        ./build_helper/github/success_msg.sh
        ls -lh /usr/bin/gcc*
