name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: '0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Cached toolchains Directory
      uses: actions/cache@v3.2.3
      with:
        path: ../toolchains_packed
        key: toolchains_packed
    - name: Setup Build Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends curl wget tar figlet
    - name: Setup toolchains
      run: ./build_helper/github/setup_toolchains.sh
    - name: Setup Build Directories
      run: ./build_helper/github/setup.sh ${{ github.event.inputs.version }}
    - name: Compile ehdd
      run: ./build_helper/github/compile.sh ${{ github.event.inputs.version }}
    - name: Compress ehdd
      run: ./build_helper/github/compress.sh ${{ github.event.inputs.version }}
    - name: Upload Release Draft
      uses: softprops/action-gh-release@v1
      with:
        name: ehdd-v${{ github.event.inputs.version }}
        tag_name: v${{ github.event.inputs.version }}
        fail_on_unmatched_files: true
        files: |
          *.tar.gz
        draft: true
        prerelease: false
